### ISSUE TITLE
[BUG] Reeder 5 iOS unable to login to FreshRSS?

### ISSUE THREAD

**Issue by Hukuma1** [marienfressinaud/FreshRSS#4105]
**Describe the bug**
Unable to get past the login screen to use Reeder 5 for iPhone with FreshRSS.

**To Reproduce**
1. Add account
2. Type in credentials
3. Sign in

**Expected behavior**
To login.

**Environment information (please complete the following information):**
- Device: iPhone 11 Pro
- OS: iOS 14.8
- Browser: [e.g. Firefox 86]
- FreshRSS version: 1.19.0
- Database version: [e.g. Mysql 5.7]
- PHP version: [e.g. PHP 7.4]
- Installation type: Linuxserver Docker

**Additional context**

```
FreshRSS API endpoints
Google Reader compatible API
Your API address:
https://freshrss.MYDOMAIN.com/api/greader.php
Google Reader API configuration test:
✔️ PASS
Fever compatible API
Your API address:
https://freshrss.MYDOMAIN.com/api/fever.php
Fever API configuration test:
✔️ PASS
```

Access.log
```
172.28.0.1 - - [31/Dec/2021:12:38:33 -0800] "POST /api/greader.php/accounts/ClientLogin HTTP/1.1" 200 126 "-" "Reeder/5010.01.03 CFNetwork/1240.0.4 Darwin/20.6.0"
172.28.0.1 - - [31/Dec/2021:12:38:33 -0800] "GET /api/greader.php/reader/api/0/user-info?output=json HTTP/1.1" 200 76 "-" "Reeder/5010.01.03 CFNetwork/1240.0.4 Darwin/20.6.0"
```

log_api.txt
```
[Fri, 31 Dec 2021 12:38:05 -0800] [warning] --- badRequest() Array
(
    [date] => 2021-12-31T12:38:05-08:00
    [headers] => Array
        (
            [Accept-Encoding] => gzip, deflate
            [Accept-Language] => en-us
            [Accept] => */*
            [User-Agent] => Reeder/5010.01.03 CFNetwork/1240.0.4 Darwin/20.6.0
            [X-Real-Ip] => 172.56.31.173
            [X-Forwarded-For] => 172.56.31.173
            [X-Forwarded-Proto] => https
            [X-Forwarded-Scheme] => https
            [Host] => freshrss.MYDOMAIN.com
            [Content-Length] => 
            [Content-Type] => 
        )

    [_SERVER] => Array
        (
            [USER] => abc
            [HOME] => /config
            [HTTP_ACCEPT_ENCODING] => gzip, deflate
            [HTTP_ACCEPT_LANGUAGE] => en-us
            [HTTP_ACCEPT] => */*
            [HTTP_USER_AGENT] => Reeder/5010.01.03 CFNetwork/1240.0.4 Darwin/20.6.0
            [HTTP_X_REAL_IP] => 172.56.31.173
            [HTTP_X_FORWARDED_FOR] => 172.56.31.173
            [HTTP_X_FORWARDED_PROTO] => https
            [HTTP_X_FORWARDED_SCHEME] => https
            [HTTP_HOST] => freshrss.MYDOMAIN.com
            [SCRIPT_FILENAME] => /usr/share/webapps/freshrss/p/api/greader.php
            [REDIRECT_STATUS] => 200
            [SERVER_NAME] => _
            [SERVER_PORT] => 80
            [SERVER_ADDR] => 172.28.0.12
            [REMOTE_PORT] => 36280
            [REMOTE_ADDR] => 172.28.0.1
            [SERVER_SOFTWARE] => nginx/1.18.0
            [GATEWAY_INTERFACE] => CGI/1.1
            [REQUEST_SCHEME] => http
            [SERVER_PROTOCOL] => HTTP/1.1
            [DOCUMENT_ROOT] => /usr/share/webapps/freshrss/p
            [DOCUMENT_URI] => /api/greader.php/accounts/ClientLogin
            [REQUEST_URI] => /api/greader.php/accounts/ClientLogin
            [SCRIPT_NAME] => /api/greader.php
            [CONTENT_LENGTH] => 
            [CONTENT_TYPE] => 
            [REQUEST_METHOD] => GET
            [QUERY_STRING] => 
            [PATH_INFO] => /accounts/ClientLogin
            [FCGI_ROLE] => RESPONDER
            [PHP_SELF] => /api/greader.php/accounts/ClientLogin
            [REQUEST_TIME_FLOAT] => 1640983085.8628
            [REQUEST_TIME] => 1640983085
        )
```

**Comment by axelsegebrecht** [comment]
Thanks for raising this, @Hukuma1. I have this issue with the desktop app also.

**Comment by Alkarex** [comment]
Hello,
Thanks for the logs @Hukuma1 and sorry for the delay.

In the `/accounts/ClientLogin` request, we expect an `Email` and `Passwd` parameters, which do not seem to be included. They must be provided either by POST or by GET. In your logs, there is no POST content.

This looks like a problem with the client or with your server setup (proxy). I can see some nginx, which is extremely error-prone.

Just as an idea, your nginx log seems to indicate a POST request, but the request arriving to FreshRSS seems to be a GET and therefore without POST payload.

To debug further, try with another client, or better, manually with cURL. See the examples of basic queries:
https://freshrss.github.io/FreshRSS/en/developers/06_GoogleReader_API.html#google-reader-compatible-api

How did you deploy FreshRSS and on which platform / versions?

See also https://freshrss.github.io/FreshRSS/en/admins/10_ServerConfig.html

**Comment by Hukuma1** [comment]
I'm a little confused. Attaching a few screenshots of Reeder and what information it's asking for in the login screen:

![reedermain](https://user-images.githubusercontent.com/54511555/149258080-453d1446-9ebe-48e3-a841-ead528f7157d.PNG)
Reeder main screen to add an account.

![reederfreshrss](https://user-images.githubusercontent.com/54511555/149258123-79955abf-8b7d-4630-ab40-44cb0063163f.PNG)
FreshRSS option. Asks for Username/Password (the API password that I set in FreshRSS)

![reedergreader](https://user-images.githubusercontent.com/54511555/149258184-d9d9f84e-1df2-4c0a-bf1a-ecb4ad8791d4.PNG)
GReader login. Asks for e-mail (not username) and password.

<img width="586" alt="freshrss" src="https://user-images.githubusercontent.com/54511555/149258477-324d8461-2be0-470e-831b-ef3f87b4f554.png">

I am unable to set an e-mail address under my account name. I can change the password and change the API password, but not set an e-mail address.

So is all this failing simply because I am unable to setup an e-mail address for my FreshRSS? I never tried to fill in it before because I didn't know the purpose of it, but now what I tried to add it, it simply isn't saving it.

<img width="655" alt="freshrss2" src="https://user-images.githubusercontent.com/54511555/149258826-93126e7b-b25e-4a49-a7a2-660b5825064e.png">


I am using Nnginx Proxy Manager to reverse proxy from my custom domain name to my self-hosted Linuxserver docker container of FreshRSS (https://hub.docker.com/r/linuxserver/freshrss). Even if I cut out my reverse proxy and plug in my local IP:PORT, it still seems to fail.

Trying a different app did work (Unread), but they only support Fever API. So not a 1:1 comparison for authentication. Logging in with Fever works on there. It asks for e-mail and password, since I had no e-mail, I just used my username. It works... Using the same info for Reeder does not. heh

**Comment by Alkarex** [comment]
You can use your FreshRSS username in the Email field

**Comment by Alkarex** [comment]
And please give a try to the cURL tests

**Comment by joshuabeny1999** [comment]
I use also the Reeder 5 App. Everything works with no issues. Instead of the Email Address I put my username and as password the API password and that works fine. I use the FreshRSS integration. 

The only issue I had first was that the feeds where not updated. But this was due I did not set up the CRON_MIN Environment Variable in my docker-compose.yaml

Due the Reeader App does not update the feeds itself. It only gets it from the Freshrss DB.

**Comment by math-GH** [comment]
How is the status? is everything solved?

**Comment by gingerbeardman** [comment]
Yesterday I logged in to my FreshRSS using Reader 5 iOS and macOS.

It's always been working.

**Comment by aledeg** [comment]
@Hukuma1 Could you confirm?

**Comment by Hukuma1** [comment]
Sorry, I've since moved on to greener pastures. :/

Happy to close this out if others have no issue with it?

**Comment by aledeg** [comment]
@Hukuma1 What are the reasons you've decided to move on? This is to know what was missing for you to stay with us. Thank you.

**Comment by aledeg** [comment]
I think we can close that for now. If this arise again, we'll reopen that issue.

**Comment by Hukuma1** [comment]
Oh no, I still use FreshRSS daily! Please keep up the excellent work. I meant I moved on from Reeder. ;)

**Comment by aledeg** [comment]
Oh! I understand. Great!

**Comment by niaodian** [comment]
I have come across the same issue as well, and I have fixed it in a easy way. My case is quite like @Hukuma1 's one, but much simple. Here we go:
1. My original api URL from FreshRSS is https://rss.example.com/api/
2. When I copy/paste the original api URL in the server address of Reeder 5, it translated the URL to http://rss.example.com/api/greader.php automatically
3. If I put the right username( not email but just my username) and API password, Reeder 5 kept showing login failure
4. After several rounds of tries, I noticed the Server URL is start with http:// but not https://
5. Then I changed the Server URL to https://rss.example.com/api/greader.php and sign in again
6. Guess what? It works!

I believe this is not a FreshRSS issue but Reeder 5's.

BTW, thanks a lot for your professional replies under this issue, it helps a lot.

**Comment by kdsub1** [comment]
Having a similar problem - cannot login to Reeder with my FreshRSS credentials.

I have allowed API access and set an API password, but it still does not allow me to log in.

I also get the below errors. How can I fix this?

<img width="519" alt="Screenshot 2024-07-14 at 8 08 40 PM" src="https://github.com/user-attachments/assets/488c853a-9ea7-4636-b85a-3912d232e649">

**Comment by Alkarex** [comment]
@kdsub1 Please open a new issue with more information about your system. Fix your `base_url` in `./data/config.php` to get rid of the warnings
