### ISSUE TITLE
[Bug] emmbed youtube video error 153

### ISSUE THREAD

**Issue by fernandeusto** [marienfressinaud/FreshRSS#8175]
### Describe the bug

The emmbed videos with youtube video extension show a 153 error and link to youtube web page

<img width="581" height="184" alt="Image" src="https://github.com/user-attachments/assets/b1054683-9bd6-4f7b-8167-2be00744fb9d" />

 

### To Reproduce

1. Install YouTube Video Feed extension
2. Add youtube chanell to rss
3. Open youtube video post
4. Error 153 is Show

### Expected behavior

View on emmbed frame

### FreshRSS version

1.27.1

### System information

- Installation type: Docker
- OS: MacOS14
- Browser: Firefox, Safari

**Comment by Inverle** [comment]
Please update the extension

See: https://github.com/FreshRSS/Extensions/pull/382

**Comment by fernandeusto** [comment]
I had already updated the extension.

In fact, in the extension file within Docker I can see this code:
<img width="885" height="234" alt="Image" src="https://github.com/user-attachments/assets/65131f5b-bcf7-4dbc-be8b-d316b81c3124" />

But when I open the video from the browser, it still shows this on F12, and I've already cleared the browser cache and tried it on computers where I've never opened FreshRSS before: 

`<iframe class="youlag-iframe" src="https://www.youtube.com/embed/XXXXXX" frameborder="0" allowfullscreen=""></iframe>`

**Comment by Inverle** [comment]
It looks like [youlag](https://github.com/civilblur/youlag) is interfering with the YT extension
Opened a PR to fix this: https://github.com/civilblur/youlag/pull/12

**Comment by fernandeusto** [comment]
That's right, it's been fixed by modifying this line in the User.js extension 

[https://github.com/civilblur/youlag/pull/12/commits/0f1140774662762ac04993676fe8ec64abee8451](url)

Thanks.

**Comment by jeffxjh** [comment]
i don't install youlag,and i see the iframe exist referrerpolicy="strict-origin-when-cross-origin", i also restart service,clear chrome appdata,hard refresh page.but still have problem.

**Comment by olivluca** [comment]
I have the same problem (error 153) but on embedded youtube videos on other feeds (e.g. hackaday or engadget).
I have installed the youtube extension but it doesn't seem to change the iframe for feeds that are not youtube feeds.
I just switched from inoreader where I could see the embedded videos.

This is the iframe from inoreader:
`<iframe allowfullscreen="allowfullscreen" title="The Waddingtons 1970s Game Machine #retrogaming" width="650" height="450" src="https://www.youtube.com/embed/QMk79fnd0VE?feature=oembed&amp;theme=light&amp;showinfo=1" frameborder="0" style="width: 650px; height: 366px;" sandbox="allow-same-origin allow-scripts allow-popups allow-forms allow-presentation"></iframe>
`

And this is the one from freshrss:
`<iframe title="The Waddingtons 1970s Game Machine #retrogaming" src="https://www.youtube.com/embed/QMk79fnd0VE?feature=oembed" frameborder="0" allow="accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" sandbox="allow-scripts allow-same-origin"></iframe>
`

**Comment by Alkarex** [comment]
@olivluca Would you be able to find out what is the meaningful difference, that is needed?

**Comment by olivluca** [comment]
Well, I cannot really say: I put both iframes in a plain html page on my personal server and I can see both videos, so it must be some other header in the http reply.

**Comment by Alkarex** [comment]
It could be due our CSP. Could you try to comment-out the following line to see whether it makes any difference?
https://github.com/FreshRSS/FreshRSS/blob/bb579956cb38258b1264adaba94e53e14b2b1004/lib/Minz/ActionController.php#L112

**Comment by olivluca** [comment]
I added the same header I get from freshrss to my server and I still can see both embedded videos (frame-src * allows loading frames from any source).

`content-security-policy: default-src 'self'; frame-src *; img-src * data: blob:; frame-ancestors 'none'; media-src *
`

if I change to `frame-src 'none'` I see nothing at all, not even the black box with error 153.

**Comment by olivluca** [comment]
Well, I'm stumped, I added all the suspicious headers to my server and I can still see both iframes

```
content-security-policy: default-src 'self'; frame-src *; img-src * data: blob:; frame-ancestors 'none'; media-src *
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block

```

**Comment by olivluca** [comment]
> It could be due our CSP. Could you try to comment-out the following line to see whether it makes any difference?

I tried, I still get the error 153 and a warning from freshrrs that I'm using an insecure csp.

**Comment by olivluca** [comment]
SInce the error comes from youtube, I checked the headers sent to them. The only difference I found is that freshrss doesn't send the "Referer" header, what causes the browser not to send it I don't know.

**Comment by Alkarex** [comment]
Could you try to comment out:
https://github.com/FreshRSS/FreshRSS/blob/bb579956cb38258b1264adaba94e53e14b2b1004/app/layout/layout.phtml#L48

**Comment by olivluca** [comment]
That was it, thank you! (actually i modified config.php but the end result is the same).

**Comment by olivluca** [comment]
Now, if only could be possible to make the iframe larger (inoreader uses 650x450 but it doesn't need to be so big) so that the youtube settings icon is visible...
oh, and the allowfullscreen option

**Comment by olivluca** [comment]
I modified SimplePieCustom.php to add the "allowfullscreen" attribute to an iframe, but I guess it's only called when fetching the article.

**Comment by Inverle** [comment]
> I have the same problem (error 153) but on embedded youtube videos on other feeds (e.g. hackaday or engadget). I have installed the youtube extension but it doesn't seem to change the iframe for feeds that are not youtube feeds. I just switched from inoreader where I could see the embedded videos.
> 
> This is the iframe from inoreader: `<iframe allowfullscreen="allowfullscreen" title="The Waddingtons 1970s Game Machine #retrogaming" width="650" height="450" src="https://www.youtube.com/embed/QMk79fnd0VE?feature=oembed&amp;theme=light&amp;showinfo=1" frameborder="0" style="width: 650px; height: 366px;" sandbox="allow-same-origin allow-scripts allow-popups allow-forms allow-presentation"></iframe> `
> 
> And this is the one from freshrss: `<iframe title="The Waddingtons 1970s Game Machine #retrogaming" src="https://www.youtube.com/embed/QMk79fnd0VE?feature=oembed" frameborder="0" allow="accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" sandbox="allow-scripts allow-same-origin"></iframe> `

https://github.com/FreshRSS/FreshRSS/issues/8289

**Comment by poulpor** [comment]
> Could you try to comment out:
> 
> [FreshRSS/app/layout/layout.phtml](https://github.com/FreshRSS/FreshRSS/blob/bb579956cb38258b1264adaba94e53e14b2b1004/app/layout/layout.phtml#L48)
> 
> Line 48 in [bb57995](/FreshRSS/FreshRSS/commit/bb579956cb38258b1264adaba94e53e14b2b1004)
>  <meta name="referrer" content="never" />

This modification still seems necessary to avoid a YouTube error 153 on certain sites. Will it be included in a future release, or does it cause other issues?

**Comment by Inverle** [comment]
> > Could you try to comment out:
> > 
> > [FreshRSS/app/layout/layout.phtml](https://github.com/FreshRSS/FreshRSS/blob/bb579956cb38258b1264adaba94e53e14b2b1004/app/layout/layout.phtml#L48)
> > 
> > Line 48 in [bb57995](/FreshRSS/FreshRSS/commit/bb579956cb38258b1264adaba94e53e14b2b1004)
> >  <meta name="referrer" content="never" />
> 
> This modification still seems necessary to avoid a YouTube error 153 on certain sites. Will it be included in a future release, or does it cause other issues?

Does https://github.com/FreshRSS/FreshRSS/pull/8672 (available since v1.29.0) resolve your issue?

**Comment by poulpor** [comment]
> > > Could you try to comment out:
> > > [FreshRSS/app/layout/layout.phtml](https://github.com/FreshRSS/FreshRSS/blob/bb579956cb38258b1264adaba94e53e14b2b1004/app/layout/layout.phtml#L48)
> > > Line 48 in [bb57995](/FreshRSS/FreshRSS/commit/bb579956cb38258b1264adaba94e53e14b2b1004)
> > 
> > 
> > This modification still seems necessary to avoid a YouTube error 153 on certain sites. Will it be included in a future release, or does it cause other issues?
> 
> Does [#8672](https://github.com/FreshRSS/FreshRSS/pull/8672) (available since v1.29.0) resolve your issue?

Darn, I had stopped at the first suggested solution without looking further, thank you for pointing me to your post and this more sustainable solution that withstands updates! It works perfectly.
